---
title: "First Knit"
author: "Luis Hernandez"
date: "September 03, 2019"
output: 
  html_document:
    number_sections: true
    toc: true
---

### `r as.character(Sys.Date())`


# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. Half the points in this assignment depend on your picture and name being correct!!  Be sure to put your photo in the AAA_Owner_Info folder and call it My_photo.jpg after first renaming the current one to Koala.jpg . 

##Where are you now?  
What row are you in, front,middle or back?  Do you usually choose a similiar row in other classes? What is the computer number where you are sitting?  How on a scale of 1 to 10 (1=low, 10=high) How you feel about periodic seat re-assignment, say how and why. Teams, have you ever worked on one in a class setting?  

###my answer     
  
I am at the back of the class, looking at the instructions for this assignemnt.
I am in the back row.
I like to sit in the same palce in all my classes.
I feel 1 on moving seats becuase I like stability.
     


##Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want me to call you something else - what would that be? 

###my answer     
  
I prefer to go by Luis   
 




##Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

###my answer     
  
I would like to build a career in a field that I enjoy.
I would really value a course in R and Phython, also a course in Geographic information systems (GIS)
 




##Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

###my answer     
  
I have been to Mexico. I would like to go to Egypt and Iceland.
I have never served in the military.
If drafted, I would like to go into the Air Force.
  



##Why are you taking Math 115?  
What grade do you need to attain in stats to not upset your future plans, What is your plan?
 

###my answer     

I am not taking Math 115 




##Homework Help and Getting around?  
On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  Do you have a computer you can use at home? If so, what kind is it (windows, Apple, Linux)? Do you have internet access at home?  
How do you get to class? Are there issues that limit when you can be at the college?Where and when did you attend high school?  Do you currently have a job?

###my answer   
  
  
I rate myself a 7 out of 10.
I have a computer at home. It is a windows computer.
I do have internet access at home.

I got to class by driving.
I do not have any issues that limit me from coming to campus.
I attended high school in Bakersfield, California.
I currently work at CSUB.



## critique of the AI in Business Article

The article discusses the use of AI in current organizations. Thousands of executives were asked if they used AI in their core activities; less than 10% of responses used AI in that way. The lack of AI use has to do with the organizational culture and barriers to change. The slow adoption of AI is also due in part to the lack of understanding of how difficult it can be to apply AI to processes that are normally only done by human labor. Additionally, for AI to be successful, it must be applied uniformly across an organization, not just parts of it. This practice may end up braking processes between departments within an organization. The major process than successful companies promote is adoption. To adopt new technologies, an organization must insure their employees are educated in the constant changes necessary to adopt AI and continue to improve with it. The article does a good job at explaining that four components required to educate an organization on the adoption process of AI (Leadership, Analytics, Translator, and End user). Adopting AI requires experts that know how to use it and how to pass on that information. It also requires the use of analytics to continuously improve the use of AI. Additionally, an organization requires translators that can use analytics for business processes. Lastly, an organization needs end users with basic knowledge of AI; enough to take care of daily tasks.  

